version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: notion-graph-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - notion-graph-network

  mongo-express:
    image: mongo-express:latest
    container_name: notion-graph-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - notion-graph-network

  redis:
    image: redis:latest
    container_name: notion-graph-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notion-graph-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: notion-graph-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - notion-graph-network

volumes:
  mongodb_data:
  redis_data:

networks:
  notion-graph-network:
    driver: bridge 